### ISSUE TITLE
flyme config 出错

### ISSUE THREAD

**Issue by jikkk86** [FlymeOS/tools#14]
> > > config
> > > Check connecting state
> > > Check adb root state
> > > Kernel root ready, run adb root
> > > restarting adbd as root
> > > Wait for the device to be online...
> > > Device is not online, wait ..
> > > device is online
> > > Root State: Kernal Root
> > > Setup the Makefile Begin!
> > > Set vendor_modify_jars: android.policy com.qti.dpmframework framework oem-services services telephony-common wifi-service
> > > awk: cmd. line:1: warning: escape sequence `\[' treated as plain`['
> > > awk: cmd. line:1: warning: escape sequence `\]' treated as plain`]'
> > > 85 KB/s (5480 bytes in 0.062s)
> > > Set RESOLUTION: 0x0
> > > # grep: Trailing backslash
> > > 
> > > Makefile Configuration:
> > >     vendor_modify_jars := android.policy com.qti.dpmframework framework oem-services services telephony-common wifi-service
> > >     vendor_saved_apps  := 
> > >     DENSITY            := 
> > > #     RESOLUTION         := 0x0
> > > 
> > > Setup the Makefile Done!
> > > Traceback (most recent call last):
> > >   File "/home/jiker/flyme/tools/pull_boot_recovery", line 10, in <module>
> > >     from pull import utils
> > >   File "/home/jiker/flyme/tools/bootimgpack/pull/utils.py", line 12, in <module>
> > >     from bootimgpack.pull.mtkpush import mtkpush
> > >   File "/home/jiker/flyme/tools/bootimgpack/pull/mtkpush.py", line 9, in <module>
> > >     from bootimgpack.pull.mtkpull import mtkpull, mtkEntry
> > >   File "/home/jiker/flyme/tools/bootimgpack/pull/mtkpull.py", line 8, in <module>
> > >     import imagetype
> > >   File "/home/jiker/flyme/tools/bootimgpack/pull/imagetype.py", line 13, in <module>
> > >     from internal.bootimg import Bootimg
> > > ImportError: cannot import name Bootimg
> > > 无法生成正确的makefile

**Comment by hexiaoshuai** [comment]
这不影响后面的工作
