### ISSUE TITLE
为什么一直提示ERR_USB_NOT_CONNECTED(151): Can not find device

### ISSUE THREAD

**Issue by nyacat** [FlymeOS/tools#3]
我已经在手机打开了adb，用adb wait-for-device也可以连上手机，并且可以直接adb shell
但是flyme config的时候一直告诉我Device is not found, Please connect device and pc with USB cable, and open Adb Debug in device.

全部输出
nyacat@nyacat-VirtualBox:~/flyme/devices/ef52l$ flyme config

> > > config
> > > Check connecting state
> > > Device is not found, Please connect device and pc with USB cable, and open Adb Debug in device.

ERR_USB_NOT_CONNECTED(151): Can not find device
Please make sure your device has been connected.

<<< config failed
nyacat@nyacat-VirtualBox:~/flyme/devices/ef52l$ flyme config

> > > config
> > > Check connecting state
> > > Device is not found, Please connect device and pc with USB cable, and open Adb Debug in device.

ERR_USB_NOT_CONNECTED(151): Can not find device
Please make sure your device has been connected.

<<< config failed

**Comment by nyacat** [comment]
而且我也试过adb kill-server

**Comment by nyacat** [comment]
自己解决了，我系统是Ubuntu 14.04.2 amd64 需要安装libc6-i386 lib32stdc++6 lib32gcc1 lib32ncurses5 lib32z1

**Comment by duanqz** [comment]
赞。
