### ISSUE TITLE
为什么会出现flyme: command not found

### ISSUE THREAD

**Issue by AUSTIN-LIN** [FlymeOS/tools#7]
下载完代码，在机型目录运行命令，无此命令，按照教程，已经配置了环境。
$ flyme config
flyme: command not found
能指点一下吗？

**Comment by zoujunhua** [comment]
检查环境变量和用户环境

**Comment by gesangtome** [comment]
没找到命令  一般为path没有加载进去   先初始化环境变量  或者你可以使用makeconfif

**Comment by gesangtome** [comment]
makeconfig
