### ISSUE TITLE
Problem Booting

### ISSUE THREAD

**Issue by boedhack99** [FlymeOS/tools#8]
I tried to build one android device sprouts, and use it as a base LMY48M 5.1.1 AOSP, with instructions that I learned all went well until there is no conflict, after completion fullota and I immediately installed it but does not boot rom, whether lord knows what happened so rom not boot ??

**Comment by shumxin** [comment]
No conflicts does not mean that device can boot normally.May you try "adb logcat > log.txt" to see some problem.
